<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ccxt" Version="4.4.73" />
    <PackageReference Include="Enums.NET" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ArbitrageScanner.Infrastructure/ArbitrageScanner.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>ArbitrageScanner.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
